# Generated by Django 5.2.2 on 2026-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('excerptTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('metaDescription', models.TextField(blank=True, null=True)),
                ('author', models.CharField(default='Adstra Digital Team', max_length=100)),
                ('publishedDate', models.DateField()),
                ('readingTime', models.CharField(default='8 min read', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
