# Generated by Django 5.2.2 on 2026-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_keywordlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordlink',
            name='link_type',
            field=models.CharField(default='internal', max_length=50),
        ),
    ]
