# Generated by Django 5.2.2 on 2025-06-09 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
