# Generated by Django 5.2.2 on 2026-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_role_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('sales_and_marketing', 'Sales And Marketing')], default='employee', max_length=30),
        ),
    ]
