# Generated by Django 5.2.2 on 2026-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Adstra Digital', max_length=255)),
                ('logo_text', models.CharField(blank=True, default='Adstra Digital', max_length=255)),
                ('certification_text', models.CharField(blank=True, default='ISO 9001:2015 & IAF Certified', max_length=255)),
                ('address', models.TextField(default='Husna Complex, 1st Floor, Nadakkavu, Kozhikode, Kerala - 673011')),
                ('gstin', models.CharField(default='32CMJPK3035L1Z2', max_length=50)),
                ('lut_no', models.CharField(blank=True, default='AD320224004945V', max_length=100)),
                ('mobile', models.CharField(default='+91 974 477 9574 | 956 756 8185', max_length=100)),
                ('email', models.EmailField(default='info.adstradigital@gmail.com', max_length=254)),
                ('bank_name', models.CharField(default='HDFC Bank', max_length=255)),
                ('account_no', models.CharField(default='50200091927202', max_length=100)),
                ('ifsc', models.CharField(default='HDFC0001595', max_length=50)),
                ('branch', models.CharField(default='Sulthan Bathery', max_length=255)),
                ('terms_conditions', models.TextField(default='1. Goods once sold will not be taken back.\n2. Payment should be made by cash or cheque in favor of Adstra Digital.\n3. Interest @ 18% p.a. will be charged if payment is not made within the due date.')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
