# Generated by Django 5.2.2 on 2026-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV-AD', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='proforma_prefix',
            field=models.CharField(blank=True, default='PI-AD', max_length=50),
        ),
    ]
