# Generated by Django 5.2.2 on 2026-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_companysettings_invoice_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_next_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='proforma_next_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV-AD-2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='proforma_prefix',
            field=models.CharField(blank=True, default='PI-AD-2026', max_length=50),
        ),
    ]
