from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Conversation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("kind", models.CharField(choices=[("DIRECT", "Direct"), ("GROUP", "Group")], max_length=10)), ("name", models.CharField(blank=True, max_length=120)), ("direct_key", models.CharField(blank=True, max_length=80, null=True, unique=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True, db_index=True)), ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_chats", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Message", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("body", models.TextField()), ("is_system", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("edited_at", models.DateTimeField(blank=True, null=True)), ("deleted_at", models.DateTimeField(blank=True, null=True)), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.conversation")), ("reply_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replies", to="chat.message")), ("sender", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_messages", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Membership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("is_admin", models.BooleanField(default=False)), ("pinned", models.BooleanField(default=False)), ("muted", models.BooleanField(default=False)), ("joined_at", models.DateTimeField(auto_now_add=True)), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="chat.conversation")), ("last_read_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="chat.message")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_memberships", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("conversation", "user"), name="unique_chat_member")]}),
        migrations.CreateModel(name="UserChatState", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("last_seen_at", models.DateTimeField(blank=True, null=True)), ("typing_expires_at", models.DateTimeField(blank=True, null=True)), ("typing_conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="typing_states", to="chat.conversation")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="chat_state", to=settings.AUTH_USER_MODEL))]),
    ]
