# Generated by Django 5.2.2 on 2026-08-05 11:31

import datetime
import uuid
from zoneinfo import ZoneInfo

import apis.leads.models
import apis.leads.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


STAGE_FORWARD = {
    'new': 'NEW',
    'contacted': 'CONTACT_ATTEMPTED',
    'qualified': 'QUALIFIED',
    'proposal': 'PROPOSAL_SENT',
    'won': 'CONVERTED',
    'lost': 'LOST',
}
STAGE_REVERSE = {value: key for key, value in STAGE_FORWARD.items()}


def migrate_legacy_leads(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    kolkata = ZoneInfo('Asia/Kolkata')
    utc = datetime.timezone.utc
    for lead in Lead.objects.all().iterator():
        follow_up_at = None
        if lead.next_follow_up:
            follow_up_at = datetime.datetime.combine(
                lead.next_follow_up,
                datetime.time(hour=9),
                tzinfo=kolkata,
            ).astimezone(utc)
        lead.lead_number = f"LD-{lead.created_at:%Y}-{uuid.uuid4().hex[:10].upper()}"
        lead.contact_person = lead.contact_name or ''
        lead.customer_name = lead.contact_name or ''
        lead.company_name = lead.company_name or ''
        lead.email = lead.email or ''
        lead.phone = lead.phone or ''
        lead.lead_type = 'SERVICE'
        lead.service = lead.service_interest or 'Legacy / unspecified service'
        lead.requirement_summary = lead.notes or ''
        lead.current_stage = STAGE_FORWARD.get(lead.status, 'NEW')
        lead.priority = (lead.priority or 'medium').upper()
        lead.estimated_value = lead.expected_value
        lead.next_follow_up_at = follow_up_at
        lead.save(update_fields=[
            'lead_number', 'contact_person', 'customer_name', 'company_name',
            'email', 'phone', 'lead_type', 'service', 'requirement_summary',
            'current_stage', 'priority', 'estimated_value', 'next_follow_up_at',
        ])


def restore_legacy_leads(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    kolkata = ZoneInfo('Asia/Kolkata')
    unsupported = sorted(
        set(Lead.objects.values_list('current_stage', flat=True)) - set(STAGE_REVERSE)
    )
    if unsupported:
        raise RuntimeError(
            "Cannot reverse advanced lead migration while unsupported stages exist: "
            + ", ".join(unsupported)
        )
    for lead in Lead.objects.all().iterator():
        lead.contact_name = lead.contact_person or lead.customer_name or 'Lead'
        lead.expected_value = lead.estimated_value
        lead.next_follow_up = (
            lead.next_follow_up_at.astimezone(kolkata).date()
            if lead.next_follow_up_at else None
        )
        lead.notes = lead.requirement_summary or None
        lead.service_interest = lead.service or lead.product or None
        lead.status = STAGE_REVERSE[lead.current_stage]
        lead.priority = (lead.priority or 'MEDIUM').lower()
        lead.save(update_fields=[
            'contact_name', 'expected_value', 'next_follow_up', 'notes',
            'service_interest', 'status', 'priority',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_date'),
        ('leads', '0001_initial'),
        ('proposal', '0011_alter_proposalsection_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCustomerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('assigned_team', models.CharField(blank=True, help_text='Existing user department/team label', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_probability',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.CharField(choices=[('TARGETED', 'Targeted'), ('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('QUALIFIED', 'Qualified'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('DEMO_COMPLETED', 'Demo Completed'), ('CUSTOMIZATION_REQUIRED', 'Customization Required'), ('REQUIREMENT_MEETING_SCHEDULED', 'Requirement Meeting Scheduled'), ('REQUIREMENT_COLLECTED', 'Requirement Collected'), ('TECHNICAL_REVIEW', 'Technical Review'), ('FEASIBILITY_REVIEW', 'Feasibility Review'), ('COST_ESTIMATION', 'Cost Estimation'), ('PROPOSAL_PREPARATION', 'Proposal Preparation'), ('PROPOSAL_SENT', 'Proposal Sent'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Negotiation'), ('DECISION_PENDING', 'Decision Pending'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='proposal.client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], db_index=True, default='SERVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Existing Proposal record used as the commercial proposal/quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='proposal.proposal'),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirement_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_before_hold',
            field=models.CharField(blank=True, choices=[('TARGETED', 'Targeted'), ('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('QUALIFIED', 'Qualified'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('DEMO_COMPLETED', 'Demo Completed'), ('CUSTOMIZATION_REQUIRED', 'Customization Required'), ('REQUIREMENT_MEETING_SCHEDULED', 'Requirement Meeting Scheduled'), ('REQUIREMENT_COLLECTED', 'Requirement Collected'), ('TECHNICAL_REVIEW', 'Technical Review'), ('FEASIBILITY_REVIEW', 'Feasibility Review'), ('COST_ESTIMATION', 'Cost Estimation'), ('PROPOSAL_PREPARATION', 'Proposal Preparation'), ('PROPOSAL_SENT', 'Proposal Sent'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Negotiation'), ('DECISION_PENDING', 'Decision Pending'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold'), ('LOST', 'Lost')], max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('UNQUALIFIED', 'Unqualified')], db_index=True, default='COLD', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, validators=[apis.leads.validators.validate_phone]),
        ),
        migrations.RunPython(migrate_legacy_leads, restore_legacy_leads),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_value',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_follow_up',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='service_interest',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(db_index=True, default=apis.leads.models.generate_lead_number, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, validators=[apis.leads.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('IMPORTED', 'Imported'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('CALL', 'Call'), ('FOLLOW_UP', 'Follow-up'), ('MEETING', 'Meeting'), ('DEMO', 'Demo'), ('REQUIREMENT', 'Requirement'), ('TECHNICAL_REVIEW', 'Technical Review'), ('COST_ESTIMATE', 'Cost Estimate'), ('APPROVAL', 'Approval'), ('PROPOSAL', 'Proposal'), ('QUOTATION', 'Quotation'), ('TASK', 'Task'), ('DOCUMENT', 'Document'), ('NOTE', 'Note'), ('STAGE_CHANGED', 'Stage Changed'), ('PUT_ON_HOLD', 'Put on Hold'), ('RESUMED', 'Resumed'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened'), ('CONVERTED', 'Converted'), ('EXPORTED', 'Exported'), ('BULK_ACTION', 'Bulk Action'), ('AUTOMATION', 'Automation')], db_index=True, default='NOTE', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignment_history_actions', to=settings.AUTH_USER_MODEL)),
                ('assigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments_from', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments_to', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='OUTBOUND', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('CONNECTED', 'Connected'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched Off'), ('INVALID_NUMBER', 'Invalid Number'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('DEMO_REQUESTED', 'Demo Requested'), ('MEETING_REQUESTED', 'Meeting Requested'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required')], max_length=40)),
                ('customer_response', models.TextField(blank=True)),
                ('discussion_summary', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('PRODUCT_ORDER', 'Product Order'), ('SERVICE_ORDER', 'Service Order'), ('PROJECT', 'Project')], max_length=40)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_terms', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.CharField(blank=True, help_text='External/future project reference', max_length=255)),
                ('sales_order', models.CharField(blank=True, help_text='External/future sales-order reference', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('converted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conversions_completed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_conversions', to='proposal.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conversions', to='invoice.invoice')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='leads.lead')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conversions', to='proposal.proposal')),
            ],
            options={
                'ordering': ['-converted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadCostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('infrastructure_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('implementation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('support_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('internal_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], db_index=True, default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lead_estimates', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='leads.lead')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_lead_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COMPANY_PROFILE', 'Company Profile'), ('REQUIREMENT', 'Requirement'), ('MEETING_MINUTES', 'Meeting Minutes'), ('TECHNICAL', 'Technical'), ('COST_ESTIMATE', 'Cost Estimate'), ('PROPOSAL', 'Proposal'), ('QUOTATION', 'Quotation'), ('CONTRACT', 'Contract'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apis.leads.models.lead_document_upload_to, validators=[apis.leads.validators.validate_document_file])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lead_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('DEMO', 'Demo'), ('REQUIREMENT_DISCUSSION', 'Requirement Discussion'), ('SITE_VISIT', 'Site Visit'), ('PROPOSAL', 'Proposal'), ('QUOTATION', 'Quotation'), ('PAYMENT', 'Payment')], max_length=40)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('purpose', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='SCHEDULED', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('PRODUCT_DEMO', 'Product Demo'), ('PRODUCT_DISCUSSION', 'Product Discussion'), ('CUSTOMIZATION_REQUIREMENT', 'Customization Requirement'), ('SERVICE_REQUIREMENT', 'Service Requirement'), ('TECHNICAL_DISCUSSION', 'Technical Discussion'), ('SITE_VISIT', 'Site Visit'), ('PROPOSAL_DISCUSSION', 'Proposal Discussion'), ('NEGOTIATION', 'Negotiation'), ('FOLLOW_UP', 'Follow-up')], db_index=True, max_length=50)),
                ('meeting_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFICE', 'Office'), ('CUSTOMER_LOCATION', 'Customer Location'), ('PHONE', 'Phone')], max_length=30)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CUSTOMER_NO_SHOW', 'Customer No-show'), ('TEAM_NO_SHOW', 'Team No-show')], db_index=True, default='SCHEDULED', max_length=30)),
                ('outcome', models.TextField(blank=True)),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_meetings', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NOT_INTERESTED', 'Not Interested'), ('INVALID_CONTACT', 'Invalid Contact'), ('NO_REQUIREMENT', 'No Requirement'), ('BUDGET_ISSUE', 'Budget Issue'), ('PRICE_TOO_HIGH', 'Price Too High'), ('COMPETITOR_SELECTED', 'Competitor Selected'), ('REQUIREMENT_POSTPONED', 'Requirement Postponed'), ('UNABLE_TO_CONTACT', 'Unable to Contact'), ('OUTSIDE_SERVICE_AREA', 'Outside Service Area'), ('PRODUCT_UNAVAILABLE', 'Product Unavailable'), ('SERVICE_UNAVAILABLE', 'Service Unavailable'), ('DUPLICATE', 'Duplicate'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('NOT_FEASIBLE', 'Not Feasible'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('detailed_notes', models.TextField()),
                ('competitor', models.CharField(blank=True, max_length=255)),
                ('rejected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recontact_allowed', models.BooleanField(default=False)),
                ('recontact_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='leads.lead')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rejected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('CALL', 'Call'), ('FOLLOW_UP', 'Follow-up'), ('MEETING', 'Meeting'), ('DEMO', 'Demo'), ('CUSTOMIZATION_REQUIREMENT', 'Customization Requirement'), ('REQUIREMENT_COLLECTION', 'Requirement Collection'), ('SITE_VISIT', 'Site Visit'), ('TECHNICAL_REVIEW', 'Technical Review'), ('FEASIBILITY_REVIEW', 'Feasibility Review'), ('COST_ESTIMATION', 'Cost Estimation'), ('APPROVAL', 'Approval'), ('PROPOSAL', 'Proposal'), ('QUOTATION', 'Quotation'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='TODO', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_version', models.CharField(blank=True, max_length=120)),
                ('customer_attendees', models.JSONField(blank=True, default=list)),
                ('requested_features', models.TextField(blank=True)),
                ('customer_pain_points', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('interest_level', models.CharField(blank=True, choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NONE', 'None')], max_length=30)),
                ('trial_requested', models.BooleanField(default=False)),
                ('trial_start', models.DateField(blank=True, null=True)),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('customization_required', models.BooleanField(default=False)),
                ('quotation_required', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('HIGHLY_INTERESTED', 'Highly Interested'), ('INTERESTED', 'Interested'), ('MORE_INFORMATION_REQUIRED', 'More Information Required'), ('TRIAL_REQUESTED', 'Trial Requested'), ('CUSTOMIZATION_REQUIRED', 'Customization Required'), ('PRICE_NEGOTIATION', 'Price Negotiation'), ('DECISION_PENDING', 'Decision Pending'), ('NOT_INTERESTED', 'Not Interested')], max_length=50)),
                ('next_action', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='leads.lead')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_demo', to='leads.leadmeeting')),
                ('presented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_product_demos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=255)),
                ('business_objective', models.TextField()),
                ('current_problem', models.TextField()),
                ('required_solution', models.TextField()),
                ('target_users', models.TextField(blank=True)),
                ('required_features', models.TextField(blank=True)),
                ('integration_requirements', models.TextField(blank=True)),
                ('technology_preference', models.CharField(blank=True, max_length=255)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('decision_maker', models.CharField(blank=True, max_length=255)),
                ('proposal_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('site_visit_required', models.BooleanField(default=False)),
                ('technical_review_required', models.BooleanField(default=False)),
                ('feasibility_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('FEASIBLE', 'Feasible'), ('FEASIBLE_WITH_CHANGES', 'Feasible with Changes'), ('NOT_FEASIBLE', 'Not Feasible')], db_index=True, default='PENDING', max_length=30)),
                ('requirement_status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COLLECTED', 'Collected'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUIRED', 'Changes Required'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requirements', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='leads.lead')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requirements', to='leads.leadmeeting')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('feasibility', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('FEASIBLE', 'Feasible'), ('FEASIBLE_WITH_CHANGES', 'Feasible with Changes'), ('NOT_FEASIBLE', 'Not Feasible')], default='PENDING', max_length=30)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_items', to='leads.lead')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='leads.servicerequirement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TargetCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32, validators=[apis.leads.validators.validate_phone])),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, validators=[apis.leads.validators.validate_phone])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('business_category', models.CharField(blank=True, max_length=160)),
                ('customer_type', models.CharField(blank=True, max_length=80)),
                ('interested_product', models.CharField(blank=True, db_index=True, max_length=255)),
                ('interested_service', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('do_not_call', models.BooleanField(db_index=True, default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_target_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='target_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.targetcustomer'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['current_stage', 'assigned_to'], name='lead_stage_assignee'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at', 'current_stage'], name='lead_followup_stage'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'campaign'], name='lead_source_campaign'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'product', 'service'], name='lead_type_offering'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'current_stage'], name='lead_created_stage'),
        ),
        migrations.AddField(
            model_name='targetcustomerlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_target_customer_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetcustomer',
            name='customer_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='leads.targetcustomerlist'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='activity_lead_created'),
        ),
        migrations.AddIndex(
            model_name='leadcall',
            index=models.Index(fields=['lead', 'started_at'], name='lead_call_started'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['status', 'scheduled_at'], name='followup_status_due'),
        ),
        migrations.AddIndex(
            model_name='leadmeeting',
            index=models.Index(fields=['status', 'scheduled_start'], name='meeting_status_start'),
        ),
        migrations.AddIndex(
            model_name='targetcustomerlist',
            index=models.Index(fields=['campaign', 'status'], name='leadlist_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='targetcustomer',
            index=models.Index(fields=['customer_list', 'assigned_to'], name='target_list_assignee'),
        ),
        migrations.AddIndex(
            model_name='targetcustomer',
            index=models.Index(fields=['source', 'priority'], name='target_source_priority'),
        ),
    ]
