# Generated by Django 5.2.2 on 2026-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_emailadvancedconfig_emailsmtpconfig_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_designations', models.JSONField(blank=True, default=list, help_text='Selected designations to show in Sales & Marketing Team view.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
