# Generated by Django 5.2.2 on 2026-08-25 06:27

import apis.leads.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_incentive_payout_and_user_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp')], default='PHONE', max_length=20)),
                ('label', models.CharField(choices=[('COMPANY', 'Company No.'), ('PERSON', 'Person Name No.'), ('OTHER', 'Other')], default='COMPANY', max_length=20)),
                ('number', models.CharField(max_length=32, validators=[apis.leads.validators.validate_phone])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_numbers', to='leads.lead')),
                ('target_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_numbers', to='leads.targetcustomer')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
