# Generated by Django 5.2.2 on 2026-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
