# Generated by Django 5.2.2 on 2026-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='designer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='script_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('script', 'Script'), ('script_approval', 'Script Approval'), ('designing', 'Scheduled / Designing'), ('team_review', 'Team Review / Ready'), ('client_review', 'Client Review'), ('approved', 'Approved / Post Schedule'), ('published', 'Published / Posted'), ('draft', 'Draft / Script'), ('internal_review', 'Team Review'), ('scheduled', 'Approved / Post Schedule'), ('publishing', 'Publishing'), ('failed', 'Failed'), ('rejected', 'Rejected / Revisions')], default='script', max_length=30),
        ),
    ]
