# Generated by Django 5.2.2 on 2026-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialpost_designer_notes_socialpost_script_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
