# Generated by Django 5.2.2 on 2026-09-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialpost_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaasset',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='social_media/%Y/%m/'),
        ),
    ]
