# Generated by Django 5.2.2 on 2026-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_socialmediaasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='script_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
