# Generated by Django 5.2.2 on 2026-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialpost_script_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclientprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
