# Generated by Django 5.2.2 on 2026-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialclientprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclientprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='brand_guidelines',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='brand_tone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='key_usps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='social_handles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialclientprofile',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
