# Generated by Django 5.2.2 on 2025-08-11 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_delete_transaction'),
        ('proposal', '0011_alter_proposalsection_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], default='receipt', help_text='Whether this is a receipt or payment', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose/description', null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.client')),
                ('invoice', models.ForeignKey(blank=True, help_text='Related invoice (optional, mainly for receipts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice.invoice')),
                ('user', models.ForeignKey(blank=True, help_text='User who received or paid', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
