# Generated by Django 5.2.2 on 2025-08-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_amount',
            new_name='balance_amount',
        ),
    ]
