# Generated by Django 5.2.2 on 2025-07-31 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_gstin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_lut',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.client'),
        ),
    ]
