# Generated by Django 5.2.2 on 2025-07-31 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_proposal_client_address_proposal_client_gstin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='client_gstin',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='client_lut',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='client_name',
        ),
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.client'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_in_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
