# Generated by Django 5.2.2 on 2025-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_alter_proposal_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
