# Generated by Django 5.2.2 on 2025-08-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_proposal_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
