# Generated by Django 5.2.2 on 2025-08-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_client_contact_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalservice',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='proposal.proposal'),
        ),
    ]
