# Generated by Django 5.2.2 on 2025-08-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0010_alter_proposalservice_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsection',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='proposal.proposal'),
        ),
    ]
