# Generated by Django 5.2.2 on 2026-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_additional_fee_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
