# Generated by Django 5.2.2 on 2026-04-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_proforma',
            field=models.BooleanField(default=False),
        ),
    ]
