# Generated by Django 5.2.2 on 2026-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoiceadditionalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceadditionalcharge',
            name='charge_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', max_length=20),
        ),
    ]
