# Generated by Django 5.2.2 on 2026-05-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoiceadditionalcharge_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_label',
            field=models.CharField(blank=True, default='Discount', max_length=255, null=True),
        ),
    ]
