# Generated by Django 5.2.2 on 2026-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_discount_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
