# Generated by Django 5.2.2 on 2025-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, default='Present', max_length=20, null=True),
        ),
    ]
