# Generated by Django 5.2.2 on 2025-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='salary_cut',
            field=models.PositiveIntegerField(default=0, help_text='Amount deducted for late check-in in INR'),
        ),
    ]
